#!/bin/bash

# Function to generate passwords.yaml
generate_passwords_yaml() {
  cat <<EOF > config/passwords.yaml
# Generated by docker-entrypoint.sh
shared:
  mySharedPassword: '${SHARED_PASSWORD:-password}'

development:
  database: '${DB_PASSWORD}'
  redis: '${REDIS_PASSWORD}'
  serviceSecret: '${SERVICE_SECRET}'
  emailSecretHashPepper: '${EMAIL_SECRET_PEPPER:-default_pepper}'
  jwtHmacSha512PrivateKey: '${JWT_PRIVATE_KEY:-default_key}'
  jwtRefreshTokenHashPepper: '${JWT_REFRESH_PEPPER:-default_pepper}'

staging:
  database: '${DB_PASSWORD}'
  serviceSecret: '${SERVICE_SECRET}'
  emailSecretHashPepper: '${EMAIL_SECRET_PEPPER:-default_pepper}'
  jwtHmacSha512PrivateKey: '${JWT_PRIVATE_KEY:-default_key}'
  jwtRefreshTokenHashPepper: '${JWT_REFRESH_PEPPER:-default_pepper}'

production:
  database: '${DB_PASSWORD}'
  serviceSecret: '${SERVICE_SECRET}'
  emailSecretHashPepper: '${EMAIL_SECRET_PEPPER:-default_pepper}'
  jwtHmacSha512PrivateKey: '${JWT_PRIVATE_KEY:-default_key}'
  jwtRefreshTokenHashPepper: '${JWT_REFRESH_PEPPER:-default_pepper}'
EOF
}

# Function to generate production.yaml
generate_production_yaml() {
  # Use defaults if not provided
  API_PORT="${API_PORT:-8080}"
  INSIGHTS_PORT="${INSIGHTS_PORT:-8081}"
  WEB_PORT="${WEB_PORT:-8082}"
  
  # For DB host, default to the variable or 'localhost'
  DB_HOST="${DB_HOST:-localhost}"
  DB_PORT="${DB_PORT:-5432}"
  DB_NAME="${DB_NAME:-serverpod}"
  DB_USER="${DB_USER:-postgres}"

  cat <<EOF > config/production.yaml
apiServer:
  port: ${API_PORT}
  publicHost: ${API_DOMAIN:-api.example.com}
  publicPort: 443
  publicScheme: https

insightsServer:
  port: ${INSIGHTS_PORT}
  publicHost: ${INSIGHTS_DOMAIN:-insights.example.com}
  publicPort: 443
  publicScheme: https

webServer:
  port: ${WEB_PORT}
  publicHost: ${WEB_DOMAIN:-app.example.com}
  publicPort: 443
  publicScheme: https

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  requireSsl: ${DB_REQUIRE_SSL:-true}

redis:
  enabled: false
  host: ${REDIS_HOST:-localhost}
  port: ${REDIS_PORT:-6379}
  user: ${REDIS_USER}
  password: ${REDIS_PASSWORD}

maxRequestSize: 524288

sessionLogs:
  consoleEnabled: false
EOF
}

echo "Generating configuration files..."
generate_passwords_yaml
generate_production_yaml

echo "Starting Serverpod..."
# Execute the command passed to the docker container (the compiled server)
# We assume the arguments are passed correctly by the CMD in Dockerfile or the platform
exec "$@"
